-- Inserir todos os tipos de template em contract_template (tabela única).
-- USE CATALOG seu_catalog;
-- USE DATABASE contract_pdf;

INSERT INTO contract_template (template_name, tipo_contrato_match, item_description, ord, created_at)
VALUES
  ('Prestação de Serviços', 'Prestação de Serviços', 'Objeto do contrato (descrição do serviço/objeto)', 1, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Valor total do contrato', 2, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Forma de pagamento', 3, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Condições de pagamento (prazos, parcelas)', 4, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Prazo de vigência', 5, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Cláusula de rescisão', 6, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Cláusula de confidencialidade', 7, current_timestamp()),
  ('Prestação de Serviços', 'Prestação de Serviços', 'Foro/jurisdição competente', 8, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Objeto do contrato (descrição do serviço/objeto)', 1, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Valor total do contrato', 2, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Forma de pagamento', 3, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Condições de pagamento (prazos, parcelas)', 4, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Prazo de vigência', 5, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Cláusula de rescisão', 6, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Cláusula de confidencialidade', 7, current_timestamp()),
  ('Fornecimento', 'Fornecimento', 'Foro/jurisdição competente', 8, current_timestamp()),
  ('Locação', 'Locação', 'Objeto do contrato (descrição do serviço/objeto)', 1, current_timestamp()),
  ('Locação', 'Locação', 'Valor total do contrato', 2, current_timestamp()),
  ('Locação', 'Locação', 'Forma de pagamento', 3, current_timestamp()),
  ('Locação', 'Locação', 'Condições de pagamento (prazos, parcelas)', 4, current_timestamp()),
  ('Locação', 'Locação', 'Prazo de vigência', 5, current_timestamp()),
  ('Locação', 'Locação', 'Cláusula de rescisão', 6, current_timestamp()),
  ('Locação', 'Locação', 'Cláusula de confidencialidade', 7, current_timestamp()),
  ('Locação', 'Locação', 'Foro/jurisdição competente', 8, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Objeto do contrato (descrição do serviço/objeto)', 1, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Valor total do contrato', 2, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Forma de pagamento', 3, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Condições de pagamento (prazos, parcelas)', 4, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Prazo de vigência', 5, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Cláusula de rescisão', 6, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Cláusula de confidencialidade', 7, current_timestamp()),
  ('Compra e Venda', 'Compra e Venda', 'Foro/jurisdição competente', 8, current_timestamp()),
  ('Outros', 'Outros', 'Objeto do contrato (descrição do serviço/objeto)', 1, current_timestamp()),
  ('Outros', 'Outros', 'Valor total do contrato', 2, current_timestamp()),
  ('Outros', 'Outros', 'Forma de pagamento', 3, current_timestamp()),
  ('Outros', 'Outros', 'Condições de pagamento (prazos, parcelas)', 4, current_timestamp()),
  ('Outros', 'Outros', 'Prazo de vigência', 5, current_timestamp()),
  ('Outros', 'Outros', 'Cláusula de rescisão', 6, current_timestamp()),
  ('Outros', 'Outros', 'Cláusula de confidencialidade', 7, current_timestamp()),
  ('Outros', 'Outros', 'Foro/jurisdição competente', 8, current_timestamp());
